apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: piers-walter-react-metrics
  app.kubernetes.io/instance: piers-walter-react-metrics
  app.kubernetes.io/name: foo
images:
- name: quay.io/account-name/repo-name
  newName: quay.io/piers_walter_ibm/react-metrics